{% set name = "jenkspy" %}
{% set version = "0.1.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'f8fa439f0ff3dc8c40bf1e24ed0b64eff44624118a88225058b000eb4d95b90c'

build:
  number: 1002
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - jenkspy

about:
  home: http://github.com/mthh/jenkspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute Natural Breaks (Jenks algorythm)
  description: "Compute natural break values (Jenks algorythm) on list/tuple/numpy.ndarray of integers/floats."
  dev_url: https://github.com/mthh/jenkspy

extra:
  recipe-maintainers:
    - nickp60
