{% set name = "jenkspy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ca1aa9480271ce62631b22f0ac9e23cc44a800d1cdfacf77f7cd409bb9461cc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython <3
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jenkspy

about:
  home: http://github.com/mthh/jenkspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute Natural Breaks (Fisher-Jenks algorithm)
  description: Compute natural breaks (Fisher-Jenks algorithm) on list/tuple/array/numpy.ndarray of integers/floats.
  dev_url: https://github.com/mthh/jenkspy

extra:
  recipe-maintainers:
    - mthh
